time_zone: UTC
time_format: ""
git_executable: /opt/homebrew/bin/git
go_executable: /opt/homebrew/bin/go
ffmpeg_executable: /opt/homebrew/bin/ffmpeg
debug_mode: false
use_github_binaries: false
architecture: ""
telegram:
    bot_token: 8031305105:AAGoTlWopPqCcwVXM3G_V2kgiZDgJZ2i5EU
    api_url: https://api.telegram.org
    sudo_users_id: []
    owner_id: 0
    target_chat_id: 0
    self_hosted_api: false
    skip_video_stickers: false
    skip_setting_commands: false
    send_my_presence: false
    send_my_read_receipts: false
    silent_confirmation: false
    confirmation_type: emoji
    emoji_confirmation: null
    skip_startup_message: false
    spoiler_as_viewonce: false
    reactions: false
whatsapp:
    login_database:
        type: sqlite3
        url: file:wawebstore.db?foreign_keys=on
    sticker_metadata:
        pack_name: WaTgBridge
        author_name: WaTgBridge
    session_name: watgbridge
    tag_all_allowed_groups: []
    ignore_chats: []
    status_ignored_chats: []
    skip_documents: false
    skip_images: false
    skip_gifs: false
    skip_videos: false
    skip_voice_notes: false
    skip_audios: false
    skip_status: false
    skip_stickers: false
    skip_contacts: false
    skip_locations: false
    skip_profile_picture_updates: false
    skip_group_settings_updates: false
    skip_chat_details: false
    send_revoked_message_updates: false
    whatsmeow_debug_mode: false
    send_my_messages_from_other_devices: false
    create_thread_for_info_updates: false
database:
    file: watgbridge.db
    type: sqlite3
