time_zone: Europe/Lisbon
time_format: 02 Jan, 2006 - Mon @ 15:04

git_executable: /usr/bin/git
go_executable: /usr/bin/go
ffmpeg_executable: /usr/bin/ffmpeg
debug_mode: false

use_github_binaries: false
architecture: amd64

telegram:
  bot_token: 8031305105:AAGoTlWopPqCcwVXM3G_V2kgiZDgJZ2i5EU # Your Telegram bot token
  self_hosted_api: false
  owner_id: 7323544557 # Replace this with your Telegram user ID
  sudo_users_id:
    - 7323544557 # Replace this with your Telegram user ID
  target_chat_id: -1002590061999 # Your Telegram group ID
  skip_video_stickers: false
  skip_setting_commands: false
  send_my_presence: false
  send_my_read_receipts: false
  silent_confirmation: true
  confirmation_type: "emoji"
  skip_startup_message: false
  spoiler_as_viewonce: true
  reactions: true

whatsapp:
  session_name: watgbridge
  tag_all_allowed_groups: [] # Add any allowed group IDs here
  ignore_chats: [] # Add any chats you want to ignore here
  status_ignored_chats: [] # Add any chats whose status updates you want to ignore
  skip_documents: false
  skip_images: false
  skip_gifs: false
  skip_videos: false
  skip_voice_notes: false
  skip_audios: false
  skip_stickers: false
  skip_status: false
  skip_contacts: false
  skip_locations: false
  skip_profile_picture_updates: false
  skip_group_settings_updates: false
  skip_chat_details: true
  send_revoked_message_updates: false
  whatsmeow_debug_mode: false
  send_my_messages_from_other_devices: false
  create_thread_for_info_updates: false
  sticker_metadata:
    pack_name: WaTgBridge
    author_name: WaTgBridge

database:
  type: sqlite
  path: ./gobot.sqlite.db
